### ISSUE TITLE
Constant variance in VMF

### ISSUE THREAD

**Issue by Ahmadrezauf** [nicola-decao/s-vae-pytorch#13]
Hello,

There is a problem with the scale neuron in vmf distribution, don't know if it's because of my data or not, but when using any type of activation function, the variance neuron will be below 0, so it will be clamped to 1, so the entropy of the distribution becomes constant. 
It's also the case for power spherical which you have pointed out in [the other thread](https://github.com/nicola-decao/s-vae-pytorch/pull/8). 
I was wondering whether this is a bug or it's also because of the numerical instabilities in the distribution.

**Comment by nicola-decao** [comment]
The scale has to be `> 0`. You should never allow your NN to predict a negative value there, as if you give an invalid scale, the behavior of the vMF and the Power Spherical is unpredictable (and invalid).

**Comment by Ahmadrezauf** [comment]
Thank you! that solved the problem. However with this change (using a non-negative activation function) the KL goes to zero even for super small KL coefficients very fast for the Power Spherical and a bit slower for the Von Misses Fisher. As a result posterior collapse happens in the VAEs. I was wondering if there is a fix for this issue.

**Comment by nicola-decao** [comment]
It depends on the problem. Maybe you need to add a regularization term in your loss to make that not happen
