### ISSUE TITLE
Numerical instability of the samples

### ISSUE THREAD

**Issue by Ahmadrezauf** [nicola-decao/s-vae-pytorch#14]
Hello,
When sampling from the VMF, sometimes the samples get super large, very far from the mean, even 1 million times bigger than the other samples from the distribution. I was wondering how can one avoid that.

**Comment by nicola-decao** [comment]
Numerical instabilities happen, and there is nothing you can do. There is a more stable distribution https://github.com/nicola-decao/power_spherical that has all the properties of the vMF but is much more stable to use. Hopefully, it will solve your problem.

**Comment by Ahmadrezauf** [comment]
Thanks a lot, I have tried that as well. However I keep getting a very unstable variance (scale) neuron, which will have a super small value, or even negative, and hence a very low and untrainable KL. I was wondering if this is a general case with these distributions or could it be specific for my dataset.

**Comment by nicola-decao** [comment]
You cannot have a negative scale. It is like the variance of a Normal distribution. By definition, it must be > 0. You should use a proper activation function to make sure of that (eg, exp).

**Comment by Ahmadrezauf** [comment]
I have tested using exp, or using a ReLU plus a very small epsilon, however the variance neuron always ends up becoming super small, so according to the definition of KL in power spherical and VMF, the KL becomes very small as well.

**Comment by nicola-decao** [comment]
That's an optimization problem it rellay depens on your loss
