### ISSUE TITLE
Hyperspherical VAE with latent dimension = 1 

### ISSUE THREAD

**Issue by mauliknariya** [nicola-decao/s-vae-pytorch#16]
Hello,

I am working on a problem that involves mapping a (very) high dimensional input layer onto a circle, latent dimension = 1, and it so happens that you have already solved this problem (Thanks!). I adapted the mnist example in this repo to z_dim=1, however, it doesn't seem to work (there is a term involving log function with the argument z_dim -1 that results into a math error). I was wondering if you could help with this. Perhaps you could share the code for the example in figure 1e of the paper "Hyperspherical Variational Auto-Encoders" if you have access to it.

I am attaching a snippet of the adapted code. Thanks!

[CycVAE.txt](https://github.com/user-attachments/files/16132185/CycVAE.txt)

**Comment by trdavidson** [comment]
Hi Maulik,Thanks for reaching out and your interest in our work!Sorry for the delayed reply, we were both traveling :). The reason it doesn’t work is that “z” represents the ambient space here, which, for a hypersphere has a minimum of 2 (a circle has x/y coordinates). The notation used is a bit counter intuitive, apologies.As a side note, I would consider using Nicola’s power spherical approximation, which should have faster sampling behavior (https://arxiv.org/abs/2006.04437).Good luck!-TimOn 8 Jul 2024, at 19:50, Maulik Nariya ***@***.***> wrote:﻿
Hello Nicola,
I am working on a problem that involves mapping a (very) high dimensional input layer onto a one dimensional circle, and it so happens that you have already solved this problem (Thanks!). I adapted the mnist example in this repo to z_dim=1, however, it doesn't seem to work (there is a term involving log function with the argument z_dim -1 that results into a math error). I was wondering if you could help with this. Perhaps you could share the code for the example in figure 1e of the paper "Hyperspherical Variational Auto-Encoders" if you have access to it.
I am attaching a snippet of the adapted code. Thanks!
CycVAE.txt

**Comment by mauliknariya** [comment]
Hi Tim,

Thanks for getting back to me. I think I understand how it works, you can
close the issue.

Best,
Maulik

**Comment by mauliknariya** [comment]
It was a shortcoming in my understanding of definition of latent space dimension.
