### ISSUE TITLE
endless loop problem

### ISSUE THREAD

**Issue by chulaihunde** [nicola-decao/s-vae-pytorch#2]
In VonMisesFisher.py

  def __while_loop(self, b, a, d, shape):
        
        b, a, d = [e.repeat(*shape, *([1] * len(self.scale.shape))) for e in (b, a, d)]
        w, e, bool_mask = torch.zeros_like(b).to(self.device), torch.zeros_like(b).to(self.device), (torch.ones_like(b) == 1).to(self.device)
        
        shape = shape + torch.Size(self.scale.shape)
 
        while bool_mask.sum() != 0:
            e_ = torch.distributions.Beta((self.__m - 1) / 2, (self.__m - 1) / 2).sample(shape[:-1]).reshape(shape).to(self.device)
            u = torch.distributions.Uniform(0, 1).sample(shape).to(self.device)
            
            w_ = (1 - (1 + b) * e_) / (1 - (1 - b) * e_)
            log_t = (2 * a * b) - (1 - (1 - b) * e_)

            accept = ((self.__m - 1) * log_t - log_t.exp() + d) > torch.log(u)
            reject = 1 - accept
            
            w[bool_mask * accept] = w_[bool_mask * accept]
            e[bool_mask * accept] = e_[bool_mask * accept]

            bool_mask[bool_mask * accept] = reject[bool_mask * accept]

**while bool_mask.sum() != 0:**

there is endless loop problem when  zdim >2

**Comment by nicola-decao** [comment]
I will investigate this issues. Thanks for pointing it out.

**Comment by aanugraha** [comment]
I believe this issue is caused by this line:
`log_t = (2 * a * b) - (1 - (1 - b) * e_)`
It should be:
`log_t = torch.log(2 * a * b) - torch.log(1 - (1 - b) * e_)`

**Comment by nicola-decao** [comment]
I think you are correct!

Indeed in my Tensorflow implementation, I have:

```
t = (2 * a * b) / (1 - (1 - b) * e)

accept = gen_math_ops.greater(((self.__mf - 1) * math_ops.log(t) - t + d), math_ops.log(u))
```

therefore I will fix the one in pytorch!

Sorry for the delay, I really appreciate the effort to investigate and pointing out the bug!

Nicola
