### ISSUE TITLE
CPU bound

### ISSUE THREAD

**Issue by giorgiop** [nicola-decao/s-vae-pytorch#3]
The current implementation of the Bessel function is on [CPU](https://github.com/nicola-decao/s-vae-pytorch/blob/master/hyperspherical_vae/ops/ive.py#L8). Do you have any workaround?

**Comment by nicola-decao** [comment]
Unfortunately not yet. The main problem is that many standard implementations of the Bessel functions are in Fortran and some of them protected by copyright. I would like to implement that on GPU one day.

However, we noticed that even with small networks, computing the Bessel function on CPU is not too time-consuming and not a bottleneck while training.

**Comment by giorgiop** [comment]
Thanks. I can confirm that small latent spaces are fine. Unfortunately training becomes unfeasible once you move to high dimension.

**Comment by pclucas14** [comment]
@giorgiop what's roughly the biggest dimension you could use without the code running too slow ?

**Comment by nicola-decao** [comment]
The rejection sampling procedure does not depend on the dimensionality (see Appendix A of the paper where we also included a table with the expected number of samples needed before acceptance). Therefore, the bottleneck won't get worse with bigger dimensions.
