### ISSUE TITLE
Derivative calculation for modified Bessel function of the first kind

### ISSUE THREAD

**Issue by amanjitsk** [nicola-decao/s-vae-pytorch#5]
Hi, 
I see you have implemented the derivative of ![Alt text](https://latex.codecogs.com/gif.latex?I_v(z)) w.r.t. ![Alt text](https://latex.codecogs.com/gif.latex?z) as

![Alt text](https://latex.codecogs.com/gif.latex?\frac{\partial&space;I_v(z)}{\partial&space;z}&space;=&space;I_{v-1}(z)&space;-&space;\frac{v&space;&plus;&space;z}{z}&space;\cdot&space;I_{v}(z))

but the derivative (confirmed by [wolfram alpha](http://functions.wolfram.com/Bessel-TypeFunctions/BesselI/20/ShowAll.html)) is given by

![Alt text](https://latex.codecogs.com/gif.latex?\frac{\partial&space;I_v(z)}{\partial&space;z}&space;=&space;I_{v-1}(z)&space;-&space;\frac{v}{z}&space;\cdot&space;I_v(z))

Is there a particular reason for the extra ![Alt text](https://latex.codecogs.com/gif.latex?z) in the gradient term or have I missed something ?

Thanks in advance,
Amanjit

**Comment by nicola-decao** [comment]
Yes, it is because we are not using the modified Bessel function but its exponentially escalated version for numerical stability. So if you compute the gradient it is a different formula. Check this out: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ive.html

**Comment by amanjitsk** [comment]
Right, figured when I read the Appendix! Thanks for the quick reply though!

**Comment by amanjitsk** [comment]
Actually, sorry to bother you on this but I found that the derivative of ![Alt text](https://latex.codecogs.com/gif.latex?I_v^{\text{exp}}(z)) to be similarly 

![Alt text](https://latex.codecogs.com/gif.latex?\frac{\partial&space;I_v^{\text{exp}}(z)}{\partial&space;z}&space;=&space;I_{v-1}^{\text{exp}}(z)&space;-&space;\frac{v&space;\pm&space;1}{z}&space;I_v^{\text{exp}}(z))

I am still not sure of the additional ![Alt text](https://latex.codecogs.com/gif.latex?z) term. Again, this might just be minor or I might just be calculating the gradient wrong. 

Thanks,
Amanjit

**Comment by amanjitsk** [comment]
I think there is a missing sign term for the extra `z` (should be `v + sign(z) * z`) term though!

**Comment by nicola-decao** [comment]
No, because for us `z` is the concentration of the von Mises-Fisher so it is `z > 0`.
