### ISSUE TITLE
GPU support 

### ISSUE THREAD

**Issue by csyanbin** [nicola-decao/s-vae-pytorch#6]
Hi,
   I run your vMF code with GPU, but encountered some problem as follows:

> hyperspherical_vae/distributions/von_mises_fisher.py", line 132, in _kl_vmf_uniform
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

Does this code support GPU computation because recent generative models rely highly on deep networks.

Thanks.

**Comment by nicola-decao** [comment]
Hi,
we originally coded in tensorflow (see https://github.com/nicola-decao/s-vae-tf which fully supported GPU training). We recently updated this repo to deal with GPUs as well. However, I cannot debug nor reproduce your error if you don't report the source you used.
